# -*- coding: utf-8 -*-
"""ARYANDUBEY_202401100700045.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rwCuxyLuWs_cejhuh9Spvan3KS1sRbY8
"""

#Grocery store Calculator
a=float(input("Enter the price of an item: "))
b=float(input("Enter the price of an item: "))
c=float(input("Enter the price of an item: "))
d=float(input("Enter the price of an item: "))
e=float(input("Enter the price of an item: "))
f=float(input("Enter the price of an item: "))
g=float(input("Enter the price of an item: "))
h=float(input("Enter the price of an item: "))
i=float(input("Enter the price of an item: "))
j=float(input("Enter the price of an item: "))
totalprice =a+b+c+d+e+f+g+h+i+j
print(totalprice) #price cannot be in negative so we have to take the price of each amount in positive values
if totalprice>10000:
   discount=totalprice*20/100
   newprice=totalprice-discount
   print("There is 20% discount over the shopping of 10000: ")
   print("New price:",newprice)
else:
  print("No discount")
  print("Total price",totalprice)