# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bIHBDtalraaRy-nuIKarqE_HU4MG1Y8x
"""

import pandas as pd
import matplotlib.pyplot as plt

# Step 1: Read the Excel file
df = pd.read_excel("Marks_secA.xlsx", skiprows=1)
df.columns = ['Roll No.', 'Name', 'Email', 'Section', 'Timestamp', 'Status', 'Marks', 'Submitted']

# Step 2: Calculate percentage
df['Percentage'] = (df['Marks'] / 15) * 100

# Step 3: Categorize students
above_75 = df[df['Percentage'] > 75]
between_60_75 = df[(df['Percentage'] >= 60) & (df['Percentage'] <= 75)]
below_60 = df[df['Percentage'] < 60]

# Step 4: Print each category
print("\n--- Students with >75% ---")
print(above_75[['Roll No.', 'Name', 'Percentage']].to_string(index=False))

print("\n--- Students with 60% to 75% ---")
print(between_60_75[['Roll No.', 'Name', 'Percentage']].to_string(index=False))

print("\n--- Students with <60% ---")
print(below_60[['Roll No.', 'Name', 'Percentage']].to_string(index=False))

# Step 5: Plot Histogram
plt.figure(figsize=(8,6))
plt.hist(df['Percentage'], bins=range(0, 105, 5), edgecolor='black', color='blue')
plt.xlabel("Percentage")
plt.ylabel("Number of Students")
plt.title("Histogram Plot")
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

# Step 6: Scatter Plot
plt.figure(figsize=(10,6))
plt.scatter(range(len(df)), df['Percentage'], color='blue', edgecolor='black')
plt.xlabel("Students")
plt.ylabel("Percentage")
plt.title("Scatter Plot")
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()